services:
  downloader:
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/database
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=sftp-files
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672//
      - SFTP_PATH=/upload/test_files
    volumes:
      - ../base/models.py:/app/base_models.py
    networks:
      - base_default

networks:
  base_default:
    external: true
