services:
  sftp-server:
    image: atmoz/sftp:latest
    restart: always
    ports:
      - "2222:22"
    environment:
      - SFTP_USERS=testuser:password:1001
    volumes:
      - sftp_data:/home/testuser/upload
      - ./test_files:/home/testuser/upload/test_files:ro
    command: testuser:password:1001
    networks:
      - smartcom_network

  sftp-client:
    image: alpine:latest
    depends_on:
      - sftp-server
    volumes:
      - ./test_files:/test_files
    command: >
      sh -c "
        apk add --no-cache openssh-client &&
        sleep 5 &&
        echo 'Creating large test files...' &&
        if [ ! -f /test_files/large_file1.bin ]; then dd if=/dev/urandom of=/test_files/large_file1.bin bs=1M count=1024; fi && \
        if [ ! -f /test_files/large_file2.bin ]; then dd if=/dev/urandom of=/test_files/large_file2.bin bs=1M count=1024; fi && \
        if [ ! -f /test_files/large_file3.bin ]; then dd if=/dev/urandom of=/test_files/large_file3.bin bs=1M count=1024; fi && \
        echo 'Large test files created successfully!' &&
        tail -f /dev/null
      "
    networks:
      - smartcom_network

volumes:
  sftp_data:

networks:
  smartcom_network:
    external: true