services:
  watchdog:
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/database
    volumes:
      - ../base/models.py:/app/base_models.py
    networks:
      - smartcom_network

networks:
  smartcom_network:
    external: true