"""Initial migration

Revision ID: 27fc6c6283aa
Revises: 
Create Date: 2025-07-20 18:55:41.011452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27fc6c6283aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False, comment='Адрес сервера'),
    sa.Column('port', sa.Integer(), nullable=False, comment='Порт для SFTP'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Имя пользователя для SFTP'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='Пароль для SFTP'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servers_id'), 'servers', ['id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servers_id', sa.Integer(), nullable=False, comment='Внешний ключ на таблицу servers'),
    sa.Column('filename', sa.String(length=500), nullable=False, comment='Имя файла'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Статус обработки'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Время создания файла'),
    sa.ForeignKeyConstraint(['servers_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_servers_id'), table_name='servers')
    op.drop_table('servers')
    # ### end Alembic commands ### 